services:
  backend:
    build:
      context: .  # Usa a raiz do projeto como contexto
      dockerfile: Dockerfile.back  # Arquivo Docker do backend
    container_name: 03-dt-money-backend-1
    ports:
      - "3333:3333"

  frontend:
    build:
      context: .  # Usa a raiz do projeto como contexto
      dockerfile: Dockerfile.front  # Arquivo Docker do frontend
    container_name: 03-dt-money-frontend-1  # ✅ Define o nome exato do container!
    ports:
      - "80:80"
    depends_on:
      - backend
