services:
  backend:
    build:
      context: .  # Usa a raiz do projeto como contexto
      dockerfile: Dockerfile.back  # Arquivo Docker do backend
    ports:
      - "3333:3333"

  frontend:
    build:
      context: .  # Usa a raiz do projeto como contexto
      dockerfile: Dockerfile.front 
       # Arquivo Docker do frontend
    ports:
      - "80:80"
    depends_on:
      - backend
