name: Deploy to AWS S3

on:
  push:
    branches:
      - "producao"  # O workflow será acionado apenas para commits na branch 'producao'
    paths:
      - "01-Ignite-feed/**"  # O workflow será acionado apenas se houver mudanças na pasta '01-Ignite-feed'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Substitua pela sua região da AWS

      - name: Deploy to S3
        run: |
          aws s3 sync ./01-Ignite-feed s3://bispo-cicd --delete
